### PR TITLE
update to embedded-cluster-operator v0.4.1

### PR DESCRIPTION
**Pull request by laverya**

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
I wonder how the e2e is working without bumping the Operator Helm Chart version in the Makefile.

**Comment by laverya** [comment]
@ricardomaraschini because if the helm chart isn't valid (and it won't be here AFAICT, whoops) it doesn't block install, just blocks that helm chart being applied

**Comment by ricardomaraschini** [comment]
OH, I see. I thought we have added a test to check the existence and consistence of the Installation/Config object.

**Review by ricardomaraschini — APPROVED** [review]

**Comment by laverya** [comment]
Nope, just a test that makes sure that the node has the label we would expect from the controller role

**Pull request merged**
