### PR TITLE
feat: preflight support for custom lam and kots ports

### PR DESCRIPTION
**Pull request by ricardomaraschini**
#### What this PR does / why we need it:

This PR depends on https://github.com/replicatedhq/embedded-cluster/pull/1205 getting merged before, that is why it is a little big longer than the usual (it includes the changes from https://github.com/replicatedhq/embedded-cluster/pull/1205).

The relevant part to be reviewed here is only the last commit ([link](https://github.com/replicatedhq/embedded-cluster/pull/1224/commits/59a927f8706a925bacc392986dce94335768a144)), the review of the other commits will be done in the other PR.

#### Does this PR require a release note?

```release-note

```

### CODE REVIEW

**Review by laverya — DISMISSED** [review]

**Comment by ricardomaraschini** [comment]
I don't want this to hold me back as there is already a follow up PR I need to raise so I am merging this. This has been previously approved by @laverya , the only thing that has changed here is some of the phrasing.

**Comment by ricardomaraschini** [comment]
@ajp-io this is how it looks like now: https://www.loom.com/share/868735275d2d466b8d0b010409d878b7

**Comment by ricardomaraschini** [comment]
> ~@ajp-io this is how it looks like now: https://www.loom.com/share/868735275d2d466b8d0b010409d878b7~

@ajp-io The previous recording was bogus, this is the actual thing: https://www.loom.com/share/bafc75d8e59e4dff9fd593e6b394a85d

**Comment by ajp-io** [comment]
Looks great! Thanks for the Loom too.

**Review by laverya — APPROVED** [review]

**Pull request merged**
